初步实现了timer unit，支持[Timer]的OnActiveSec,  OnUnitInactiveSec, OnUnitActiveSec,  Unit,字段
DragonOS-Community/DragonReach pull request #44
Opened 2024-04-26 09:59 UTC by BrahmaMantra

此时会在parse的时候启用所有计时器，要给shell.service配置相应的shell.timer计时器才能启动shell，后续再实现通过systemctl的方法启用。目前在linux上测试没有问题，但无法在DragonOs顺利运行，疑似是内核空间的time实现有点小bug，导致时间不准确（甚至经常在1s内调用Instant::now()会差了9000s），等待后续完善

2024-04-26 10:26 UTC, fslongjin commented
有两个问题，
1. PR的名字应当按照DragonOS开发文档里面参与开发那个指南里面的相关内容，加上前缀
2. 应当要把任务的issue链接贴到PR的描述里

2024-04-26 11:24 UTC, fslongjin commented
提交代码之前要cargo fmt并且解决warning哈

2024-04-26 11:25 UTC, fslongjin commented
> 疑似是内核空间的time实现有点小bug，导致时间不准确（甚至经常在1s内调用Instant::now()会差了9000s）

能否写个小的测试程序，单独开一个仓库，然后把这个问题复现了，接着在dragonos那个仓库那里提issue

2024-04-26 15:35 UTC, BrahmaMantra commented
收到（pr前检查时加了个注释忘记fmt了0.0）

2024-04-28 10:06 UTC, BrahmaMantra commented
#41

2024-04-28 10:07 UTC, BrahmaMantra commented
This resolves #41

2024-04-28 17:54 UTC, GnoCiYeH requested changes
整体看了一遍，有一些问题，需要注意的是，这个程序是主要跑在DragonOS的，需要再DragonOS实际测试，最好有测试用例。

2024-04-28 17:54 UTC, GnoCiYeH commented on src/main.rs
> +        if id != 0 && TimerManager::is_timer(&id) {
这个地方是否有些问题，目前的写法是如果不是timer就不会运行了，这个问题如果在DragonOS测试过的话应该能够第一时间发现的。。

2024-04-28 17:54 UTC, GnoCiYeH commented on src/main.rs
> +//const DRAGON_REACH_UNIT_DIR: &'static str = "/home/fz/testSystemd/";
这种临时的注释需要删除

2024-04-28 17:54 UTC, GnoCiYeH commented on src/manager/timer_manager/mod.rs
> +        let mut unit_ = unit.lock().unwrap();
这个命名为``unit_guard``更合适

2024-04-28 17:54 UTC, GnoCiYeH commented on src/manager/unit_manager/mod.rs
> +    // ↑感觉是笔误，应该是通过path获取到id
哈哈哈笔误，可以直接改一下<

2024-04-28 17:54 UTC, GnoCiYeH commented on src/unit/timer/mod.rs
> +        return self.timer_part.set_attr(attr_type.unwrap(), val);
这里不应该``unwrap``，应该是向上层抛出，不然别人特意捏一个错误信息，程序就直接就崩了。

2024-04-29 01:56 UTC, BrahmaMantra commented on src/main.rs
> +        if id != 0 && TimerManager::is_timer(&id) {
测试过的，我暂时打算一个service配置一个timer，便于测试OnActiveSec的效果

2024-05-01 07:20 UTC, GnoCiYeH commented on src/main.rs
> +        if id != 0 && TimerManager::is_timer(&id) {
但是如果现在这个PR合并的话，在DragonOS是跑不了的，所以你可能得先适配一下

2024-05-19 07:01 UTC, GnoCiYeH approved these changes

2024-05-19 07:04 UTC, GnoCiYeH requested changes

2024-05-19 07:04 UTC, GnoCiYeH commented on src/unit/timer/mod.rs
> +        // 从给定的路径解析并创建计时器单元
这种注释，标注在函数声明上方更为规范~

2024-05-19 07:04 UTC, GnoCiYeH commented on src/unit/timer/mod.rs
> +        // 重启单元
同理

2024-05-19 07:05 UTC, GnoCiYeH commented
整体代码很ok，注释的风格可以更加规范一点~，然后就是我在DragonOS测试的时候，发现设置的5s但是触发时间很不稳点，这个bug可以看一看是内核还是dragonreach实现的问题

2024-05-19 07:25 UTC, fslongjin commented
> 整体代码很ok，注释的风格可以更加规范一点~，然后就是我在DragonOS测试的时候，发现设置的5s但是触发时间很不稳点，这个bug可以看一看是内核还是dragonreach实现的问题

这个之前确定了是内核问题，但是不知道为啥还没PR @BrahmaMantra

2024-05-19 07:39 UTC, BrahmaMantra commented
> > 整体代码很ok，注释的风格可以更加规范一点~，然后就是我在DragonOS测试的时候，发现设置的5s但是触发时间很不稳点，这个bug可以看一看是内核还是dragonreach实现的问题
> 
> 这个之前确定了是内核问题，但是不知道为啥还没PR @BrahmaMantra

我滴锅，现在就去

2024-05-19 07:42 UTC, GnoCiYeH approved these changes

2024-05-20 09:10 UTC, merged